name: "Build & Release"
on:
  push:
    tags:
      - "v*"

permissions:
  contents: write # Add this line for release permissions

jobs:
  build-tauri:
    strategy:
      matrix:
        platform: [windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: Install frontend dependencies
        run: npm ci

      - name: Build Tauri app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: ${{ github.ref_name }}
          releaseName: "Boostify ${{ github.ref_name }}"
          releaseBody: |
            Boostify v1.0.0 - System Power Optimization Tool

            **Features:**
            - Advanced processor boost mode control
            - Maximum processor state management
            - AC/DC power profile switching
            - Real-time power optimization
            - User-friendly interface

            **Requirements:**
            - Windows 10/11
            - Administrator privileges for power management
          releaseDraft: true
          prerelease: false
