name: "Build & Release"
on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build-tauri:
    strategy:
      matrix:
        platform: [windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: clippy

      - name: Install dependencies (Windows)
        if: matrix.platform == 'windows-latest'
        run: |
          npm ci
          rustup target add x86_64-pc-windows-msvc

      - name: Build Tauri app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
        with:
          tagName: ${{ github.ref_name }}
          releaseName: "Boostify ${{ github.ref_name }}"
          releaseBody: |
            Boostify v1.0.0 - System Power Optimization Tool

            **Features:**
            - Advanced processor boost mode control
            - Maximum processor state management
            - AC/DC power profile switching
            - Real-time power optimization
            - User-friendly interface

            **Requirements:**
            - Windows 10/11
            - Administrator privileges for power management

            **Changes in this version:**
            - Migrated to pure Rust implementation
            - Improved error handling
            - Better performance and stability
            - Enhanced security
          releaseDraft: true
          prerelease: false

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.platform }}-bundle
          path: |
            src-tauri/target/release/bundle/msi/*
            src-tauri/target/release/bundle/nsis/*
